AWSTemplateFormatVersion: 2010-09-09
Description: This template creates the infrastructure required to implement and test
  SageMaker Studio VPC Mode. It creates a VPC, Subnet, VPC Endpoints, VPC Policies,
  and IAM Execution Roles. **WARNING** This template creates AWS Resources in your
  account. You will be billed for the AWS resources used if you create a stack from
  this template.
Parameters:
  ProjectName:
    Type: String
    Default: sagemaker-studio-vpc
  VpcCIDR:
    Type: String
    Default: 10.2.0.0/16
  FirewallSubnetCIDR:
    Type: String
    Default: 10.2.1.0/24
  NATGatewaySubnetCIDR:
    Type: String
    Default: 10.2.2.0/24
  SageMakerStudioSubnetCIDR:
    Type: String
    Default: 10.2.3.0/24
Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        DataBucket:
          Fn::GetAtt:
          - S3
          - Outputs.DataBucket
        ModelBucket:
          Fn::GetAtt:
          - S3
          - Outputs.ModelBucket
      TemplateURL: https://s3.eu-central-1.amazonaws.com/ilyiny-sagemaker-demo-artefacts/57c275518cd27f0c6a229f6d6431fe2b.template
  S3:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        DataBucketName:
          Fn::GetAtt:
          - VPC
          - Outputs.DataBucket
        ModelBucketName:
          Fn::GetAtt:
          - VPC
          - Outputs.ModelBucket
      TemplateURL: https://s3.eu-central-1.amazonaws.com/ilyiny-sagemaker-demo-artefacts/c30fb1e65c276aacdec6edf90cff7ff3.template
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        VpcCIDR:
          Ref: VpcCIDR
        FirewallSubnetCIDR:
          Ref: FirewallSubnetCIDR
        NATGatewaySubnetCIDR:
          Ref: NATGatewaySubnetCIDR
        SageMakerStudioSubnetCIDR:
          Ref: SageMakerStudioSubnetCIDR
        DataBucketName:
          Fn::Sub: ${ProjectName}-${AWS::Region}-data
        ModelBucketName:
          Fn::Sub: ${ProjectName}-${AWS::Region}-models
      TemplateURL: https://s3.eu-central-1.amazonaws.com/ilyiny-sagemaker-demo-artefacts/473d5d7e0d9951d321817f7ce88f65d1.template
Outputs:
  VPCId:
    Description: The ID of VPC where SageMaker Studio will reside
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VPCId
  SageMakerStudioSubnetId:
    Description: The ID of the SageMaker subnet
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.SageMakerStudioSubnetId
  SageMakerStudioSecurityGroupId:
    Description: The ID the SageMaker security group
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.SageMakerSecurityGroupId
  SageMakerExecutionRoleArn:
    Description: IAM Execution role for SageMaker Studio and SageMaker notebooks
    Value:
      Fn::GetAtt:
      - IAM
      - Outputs.ExecutionRoleArn
  KMSCMKEBSArn:
    Description: KMS CMK arn for SageMaker notebooks EBS encryption
    Value:
      Fn::GetAtt:
      - IAM
      - Outputs.KMSKeyArn
  KMSCMKS3bucketsArn:
    Description: KMS CMK arn for data encryption in S3 buckets
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.KMSKeyArn
  SageMakerS3bucketData:
    Description: Name of S3 bucket for data
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.DataBucket
  SageMakerS3bucketModels:
    Description: Name of S3 bucket for models
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.ModelBucket
