AWSTemplateFormatVersion: 2010-09-09
Description: Amazon SageMaker Studio secure deployment demo. The deployment creates
  all necessary network infrastructure and SageMaker Studio domain.
Parameters:
  ProjectName:
    Type: String
    Default: sagemaker-studio-vpc
  DomainName:
    Description: SageMaker domain name
    Type: String
    Default: sagemaker-demo-domain
  UserProfileName:
    Description: User profile name for the SageMaker domain
    Type: String
    Default: demouser-profile
  VpcCIDR:
    Type: String
    Default: 10.2.0.0/16
  FirewallSubnetCIDR:
    Type: String
    Default: 10.2.1.0/24
  NATGatewaySubnetCIDR:
    Type: String
    Default: 10.2.2.0/24
  SageMakerStudioSubnetCIDR:
    Type: String
    Default: 10.2.3.0/24
Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        DataBucketName:
          Fn::GetAtt:
          - S3
          - Outputs.DataBucketName
        ModelBucketName:
          Fn::GetAtt:
          - S3
          - Outputs.ModelBucketName
      TemplateURL: https://s3.us-west-2.amazonaws.com/ilyiny-sagemaker-demo-artefacts-us-west-2/fd5f4b9f56bf2d8b33f377fabb9d291a.template
  S3:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        DataBucketName:
          Fn::GetAtt:
          - VPC
          - Outputs.DataBucketName
        ModelBucketName:
          Fn::GetAtt:
          - VPC
          - Outputs.ModelBucketName
      TemplateURL: https://s3.us-west-2.amazonaws.com/ilyiny-sagemaker-demo-artefacts-us-west-2/56115a0619e778bdc0fa99c260aa02a7.template
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        VpcCIDR:
          Ref: VpcCIDR
        FirewallSubnetCIDR:
          Ref: FirewallSubnetCIDR
        NATGatewaySubnetCIDR:
          Ref: NATGatewaySubnetCIDR
        SageMakerStudioSubnetCIDR:
          Ref: SageMakerStudioSubnetCIDR
        DataBucketName:
          Fn::Sub: ${ProjectName}-${AWS::Region}-data
        ModelBucketName:
          Fn::Sub: ${ProjectName}-${AWS::Region}-models
      TemplateURL: https://s3.us-west-2.amazonaws.com/ilyiny-sagemaker-demo-artefacts-us-west-2/3d0d58eb15d519e575bfec9108c84606.template
  SageMakerStudio:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAM
    Properties:
      Parameters:
        DomainName:
          Fn::Sub: ${DomainName}-${AWS::Region}
        UserProfileName:
          Fn::Sub: ${UserProfileName}-${AWS::Region}
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VPCId
        SageMakerStudioSubnetIds:
          Fn::GetAtt:
          - VPC
          - Outputs.SageMakerStudioSubnetId
        SageMakerSecurityGroupIds:
          Fn::GetAtt:
          - VPC
          - Outputs.SageMakerSecurityGroupId
        SageMakerExecutionRoleArn:
          Fn::GetAtt:
          - IAM
          - Outputs.ExecutionRoleArn
      TemplateURL: https://s3.us-west-2.amazonaws.com/ilyiny-sagemaker-demo-artefacts-us-west-2/9df4e5d352738f0ff537059d5599fa82.template
Outputs:
  VPCId:
    Description: The ID of VPC where SageMaker Studio will reside
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VPCId
  SageMakerStudioSubnetId:
    Description: The ID of the SageMaker subnet
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.SageMakerStudioSubnetId
  SageMakerStudioSecurityGroupId:
    Description: The ID the SageMaker security group
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.SageMakerSecurityGroupId
  SageMakerExecutionRoleArn:
    Description: IAM Execution role for SageMaker Studio and SageMaker notebooks
    Value:
      Fn::GetAtt:
      - IAM
      - Outputs.ExecutionRoleArn
  KMSCMKEBSArn:
    Description: KMS CMK arn for SageMaker notebooks EBS encryption
    Value:
      Fn::GetAtt:
      - IAM
      - Outputs.KMSKeyArn
  KMSCMKS3bucketsArn:
    Description: KMS CMK arn for data encryption in S3 buckets
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.KMSKeyArn
  SageMakerS3bucketData:
    Description: Name of S3 bucket for data
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.DataBucketName
  SageMakerS3bucketModels:
    Description: Name of S3 bucket for models
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.ModelBucketName
  SageMakerStudioDomainId:
    Description: SageMaker Studio domain id
    Value:
      Fn::GetAtt:
      - SageMakerStudio
      - Outputs.SageMakerStudioDomainId
  UserProfileName:
    Description: SageMaker user profile name
    Value:
      Fn::GetAtt:
      - SageMakerStudio
      - Outputs.UserProfileName
