AWSTemplateFormatVersion: 2010-09-09
Description: This template creates the infrastructure required to implement and test
  SageMaker Studio VPC Mode. It creates a VPC, Subnet, VPC Endpoints, VPC Policies,
  and IAM Execution Roles. **WARNING** This template creates AWS Resources in your
  account. You will be billed for the AWS resources used if you create a stack from
  this template.
Parameters:
  ProjectName:
    Type: String
    Default: sagemaker-studio-vpc
  DomainName:
    Description: SageMaker domain name
    Type: String
    Default:
      Fn::Sub: sagemaker-domain-${AWS::Region}
  UserProfileName:
    Description: User profile name for the SageMaker domain
    Type: String
    Default:
      Fn::Sub: demouser-profile-${AWS::Region}
  VpcCIDR:
    Type: String
    Default: 10.2.0.0/16
  FirewallSubnetCIDR:
    Type: String
    Default: 10.2.1.0/24
  NATGatewaySubnetCIDR:
    Type: String
    Default: 10.2.2.0/24
  SageMakerStudioSubnetCIDR:
    Type: String
    Default: 10.2.3.0/24
Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        DataBucketName:
          Fn::GetAtt:
          - S3
          - Outputs.DataBucketName
        ModelBucketName:
          Fn::GetAtt:
          - S3
          - Outputs.ModelBucketName
      TemplateURL: https://s3.eu-west-1.amazonaws.com/ilyiny-sagemaker-demo-artefacts/3c3445cd49c64d342dbb06e35901e81b.template
  S3:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        DataBucketName:
          Fn::GetAtt:
          - VPC
          - Outputs.DataBucketName
        ModelBucketName:
          Fn::GetAtt:
          - VPC
          - Outputs.ModelBucketName
      TemplateURL: https://s3.eu-west-1.amazonaws.com/ilyiny-sagemaker-demo-artefacts/56115a0619e778bdc0fa99c260aa02a7.template
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName:
          Ref: ProjectName
        VpcCIDR:
          Ref: VpcCIDR
        FirewallSubnetCIDR:
          Ref: FirewallSubnetCIDR
        NATGatewaySubnetCIDR:
          Ref: NATGatewaySubnetCIDR
        SageMakerStudioSubnetCIDR:
          Ref: SageMakerStudioSubnetCIDR
        DataBucketName:
          Fn::Sub: ${ProjectName}-${AWS::Region}-data
        ModelBucketName:
          Fn::Sub: ${ProjectName}-${AWS::Region}-models
      TemplateURL: https://s3.eu-west-1.amazonaws.com/ilyiny-sagemaker-demo-artefacts/f8515d45bd513b0a30bdbdca648eee06.template
  SageMakerStudio:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAM
    Properties:
      Parameters:
        DomainName:
          Ref: DomainName
        UserProfileName:
          Ref: UserProfileName
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VPCId
        SageMakerStudioSubnetIds:
          Fn::GetAtt:
          - VPC
          - Outputs.SageMakerStudioSubnetId
        SageMakerSecurityGroupIds:
          Fn::GetAtt:
          - VPC
          - Outputs.SageMakerSecurityGroupId
        SageMakerExecutionRoleArn:
          Fn::GetAtt:
          - IAM
          - Outputs.ExecutionRoleArn
      TemplateURL: https://s3.eu-west-1.amazonaws.com/ilyiny-sagemaker-demo-artefacts/d86a37290c0f220ab51858ddbbe54da4.template
Outputs:
  VPCId:
    Description: The ID of VPC where SageMaker Studio will reside
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VPCId
  SageMakerStudioSubnetId:
    Description: The ID of the SageMaker subnet
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.SageMakerStudioSubnetId
  SageMakerStudioSecurityGroupId:
    Description: The ID the SageMaker security group
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.SageMakerSecurityGroupId
  SageMakerExecutionRoleArn:
    Description: IAM Execution role for SageMaker Studio and SageMaker notebooks
    Value:
      Fn::GetAtt:
      - IAM
      - Outputs.ExecutionRoleArn
  KMSCMKEBSArn:
    Description: KMS CMK arn for SageMaker notebooks EBS encryption
    Value:
      Fn::GetAtt:
      - IAM
      - Outputs.KMSKeyArn
  KMSCMKS3bucketsArn:
    Description: KMS CMK arn for data encryption in S3 buckets
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.KMSKeyArn
  SageMakerS3bucketData:
    Description: Name of S3 bucket for data
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.DataBucketName
  SageMakerS3bucketModels:
    Description: Name of S3 bucket for models
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.ModelBucketName
  SageMakerStudioDomainId:
    Description: SageMaker Studio domain id
    Value:
      Fn::GetAtt:
      - SageMakerStudio
      - SageMakerStudioDomainId
  SageMakerStudioPresignedURL:
    Description: Presigned-URL to start the Amazon SageMaker Studio
    Value:
      Fn::GetAtt:
      - SageMakerStudio
      - SageMakerStudioPresignedURL
