AWSTemplateFormatVersion: 2010-09-09
Description: "This template creates the infrastructure required to implement and test SageMaker Studio VPC Mode. 
  It creates a VPC, Subnet, VPC Endpoints, VPC Policies, and IAM Execution Roles. 
  **WARNING** This template creates AWS Resources in your account. 
  You will be billed for the AWS resources used if you create a stack from this template."

Parameters:
  ProjectName:
    Type: String
    Default: sagemaker-studio-vpc
  VpcCIDR:
    Type: String
    Default: 10.2.0.0/16
  FirewallSubnetCIDR:
    Type: String
    Default: 10.2.1.0/24
  NATGatewaySubnetCIDR:
    Type: String
    Default: 10.2.2.0/24
  SageMakerStudioSubnetCIDR:
    Type: String
    Default: 10.2.3.0/24

Resources:
  #================================================================================
  # IAM ROLE AND KMS ENCRYPTION KEY 
  #================================================================================
  IAM:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        DataBucket: !GetAtt S3.Outputs.DataBucket
        ModelBucket: !GetAtt S3.Outputs.ModelBucket
      TemplateURL:  iam.yaml
  #================================================================================
  # S3 BUCKETS - DATA BUCKET AND MODEL BUCKET 
  #================================================================================
  S3:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        DataBucketName: !GetAtt VPC.Outputs.DataBucket
        ModelBucketName: !GetAtt VPC.Outputs.ModelBucket
      TemplateURL:  s3.yaml
  #================================================================================
  # VPC WITH A PRIVATE SUBNET AND SECURITY GROUP 
  #================================================================================
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        VpcCIDR: !Ref VpcCIDR
        FirewallSubnetCIDR: !Ref FirewallSubnetCIDR
        NATGatewaySubnetCIDR: !Ref NATGatewaySubnetCIDR
        SageMakerStudioSubnetCIDR: !Ref SageMakerStudioSubnetCIDR
        DataBucketName: !Sub ${ProjectName}-${AWS::Region}-data
        ModelBucketName: !Sub ${ProjectName}-${AWS::Region}-models
      TemplateURL:  vpc.yaml

Outputs:
  VPCId:
    Description: The ID of VPC where SageMaker Studio will reside
    Value: !GetAtt VPC.Outputs.VPCId
  SageMakerStudioSubnetId:
    Description: The ID of the SageMaker subnet
    Value: !GetAtt VPC.Outputs.SageMakerStudioSubnetId
  SageMakerStudioSecurityGroupId:
    Description: The ID the SageMaker security group
    Value: !GetAtt VPC.Outputs.SageMakerSecurityGroupId
  SageMakerExecutionRoleArn:
    Description: IAM Execution role for SageMaker Studio and SageMaker notebooks
    Value: !GetAtt IAM.Outputs.ExecutionRoleArn
  KMSCMKEBSArn:
    Description: KMS CMK arn for SageMaker notebooks EBS encryption
    Value: !GetAtt IAM.Outputs.KMSKeyArn
  KMSCMKS3bucketsArn:
    Description: KMS CMK arn for data encryption in S3 buckets
    Value: !GetAtt S3.Outputs.KMSKeyArn
  SageMakerS3bucketData:
    Description: Name of S3 bucket for data
    Value: !GetAtt S3.Outputs.DataBucket
  SageMakerS3bucketModels:
    Description: Name of S3 bucket for models
    Value: !GetAtt S3.Outputs.ModelBucket
